services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: cart-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - cart_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  cart-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cart-db
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  cart_postgres_data: